[package]
name = "curlplusplus"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
crossterm = "0.29.0"
fern = "0.7.1"
log = "0.4.29"
openapi = "0.1.5"
ratatui = "0.29.0"
reqwest = "0.12.24"
ropey = "1.6.1"
serde_json = "1.0.145"
